name: FunkyTown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51439
title: ITS ALL ABOUT DANCE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#542700'
    - '#7f6504'
    - '#c71a2d'
    - '#d9a929'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
