title: ITS ALL ABOUT DANCE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#ffffff'
    - '#542700'
    - '#7f6504'
    - '#c71a2d'
    - '#d9a929'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: FunkyTown
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9211469
layout_spectrum: 1
